### ISSUE TITLE
Support for `f32` in FFT computations

### ISSUE THREAD

**Issue by astral4** [QuState/PhastFT#12]
In [`rustfft`](https://crates.io/crates/rustfft), it's possible to compute Fourier transforms of sequences with either 32-bit or 64-bit floats. This is done by generalizing over an [`FftNum`](https://docs.rs/rustfft/6.2.0/rustfft/trait.FftNum.html) trait. However, `phastft` only supports 64-bit floats. Is it possible to add support for `f32` in `phastft`?

**Comment by smu160** [comment]
Hi @astral4,

That's a great point. Since we also need `f32` support for [Spinoza](https://github.com/QuState/spinoza), this is next on my to-do list.

Thank you!

Best,
Saveliy
